### ISSUE TITLE
Rogue - Lay Trap not working

### ISSUE THREAD

**Issue by vitortexc** [Kathanious/DAIL2#12]
Hi,

I don't know if it is a problem of DAIL or Grim Quest mod, but I decided to post here since GQ version didn't change from your version 58 until now.

For some reason the Lay Trap skill isn't working in version 60.1+.
Whenever one is summoned, it never attack or desappear.

It was working on version 58.3, but stopped when updated to 60.1.
Tried updating to the new 60.2 with the 60.3 hotfix, but still nothing.

Could you please see if there are any fix for it? Thanks.

**Comment by Kathanious** [comment]
Asylum101, the dev for GQ, made some changes to the trap as part of his ongoing development of the mod. This is a known issue to him and I believe it is fixed in the next GQ release (hopefully soon).

**Comment by vitortexc** [comment]
Thanks for the response. Waiting to see if it will be fixed with other bugs I found.

:)
