### ISSUE TITLE
Report bug :P

### ISSUE THREAD

**Issue by Duz1NN** [Kathanious/DAIL2#13]
Kathanious, whenever DAIL updates I delete the old folders (when necessary) and paste the new one, so that it does not find any problem. And also always create new char so you can test everything right and be able to report if you discover a bug.
As you know, I've been playing RIFT mod for quite some time, this game mode has caught my attention, I like it a lot. Congratulations to the person who created it.
Speaking of creation, the two new classes added, are sensational, very good. If it were possible to add them permanently, it would be great.
But I came here to talk about a bug that happened to me, I created a char, I was playing in RIFT mode, VETERANO difficulty, and I realized that I was not gaining a reputation in USER 14, but I'm gaining a reputation with USER 15 that would be the reputation of the enemy.
In the last version I did not gain reputation in the veteran level, I began to gain reputation in the USER14 only after the ELITE, in that version 60 I am not gaining reputation in him, nor in ELITE and ULTIMATE.
Not gaining a reputation in this USER14 can be very complicated the game, because I will take a lot to create the Relics and also use the materials in the items, because it is very difficult to drop the materials.
This is the problem that is happening to me ^^
And I'm always sorry that I'm going to report, I make these great texts, I like to explain things
Thanks again :D

**Comment by Kathanious** [comment]
I have heard similar reports. When I test played 60.4, I was getting user14 and user15 faction. If you notice you are not getting faction from killing heroes and bosses, try reloading Grim Dawn and DGA and see if that fixes the problem.
