### ISSUE TITLE
Report problem with installation

### ISSUE THREAD

**Issue by Duz1NN** [Kathanious/DAIL2#15]
When I installed the new version 60.4, I always play with the "S" mode, but inside the game where it shows the difficulty at the top of the screen, it was "ELITE NG", I deleted the DAIL folders, I entered the game and continued "NG", then I tried the others, X, SX .. all continued as "NG" up there, I do not think it is a visual bug.
You know what I can do to fix it?

**Comment by Kathanious** [comment]
As long as the mob density and challenge is correct, the tag in the corner is likely a failure on my part to update the text file.
