### ISSUE TITLE
Report Bug

### ISSUE THREAD

**Issue by Duz1NN** [Kathanious/DAIL2#2]
Well Kathanious , You remember a report of me on the RIFT mod, that I was not able to play the ENDLESS mode, I tried several times to enter the endless mode, and when I enter the map, it's all empty, there are no mobs, and there's no way back To the city, I need to quit the game and log in again, I tried to repeat this process to see if any time I could respawn the mobs there, but without success, I tried more than 20 times and no time the mobs appeared.
I downloaded the latest 58.3F version, but up there where it shows the difficulty of the game is still showing (ELITE S54), well, I deleted all the DAIL folders, and downloaded everything new, the version is the new 58.3F, but Up there on the difficulty still shows S54.
Is that why you're not respawning on mobs in ENDLESS MODS?

Thanks for continuing to update the mod, I hope some new update will come back to working that endless mode so I'm very curious to play it. :D

**Comment by Kathanious** [comment]
This is only on DGA endless, and not the regular tiers?

**Comment by Duz1NN** [comment]
Yes , Do you have any idea what it might be?

**Comment by Kathanious** [comment]
I'll have to look and see if any files are missing.

**Comment by Kathanious** [comment]
If you are a steam user, try verifying file integrity.

**Comment by Duz1NN** [comment]
I tried , and nothing , not are missing any file :/

**Comment by Duz1NN** [comment]
hey Kathanious I have a doubt, do not know if my game bug, or if there has been any change in reputations, as I said above I play the RIFT mode, and the reputations there, are not the same as the campaign.
Every Hero / Boss I kill appears on the screen +1 reputation player 14 or 15.
Honestly I think 1 point for each hero / boss is very little, I do not want it to be easy, but I think if you find a balance this would be the best.
For example 3 points for each Hero and 5 points for each Boss, even those values would not make the game easy.
What do you think?

**Comment by Kathanious** [comment]
DGA has its own faction system

**Comment by Kathanious** [comment]
I tested DGA Endless straight from the source as a stand-alone mod and endless does not work their either. It may be an incomplete function. I know WareBare has picked up his DGA project again, so hopefully we'll so this function completed.
