### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by Duz1NN** [Kathanious/DAIL2#30]
This dropping items and relics with '' TAG NOT FOUND '', is not uncommon to drop, I have dropped quite a lot of these items, mainly relics ...
If you can fix it, I thank you very much.
![tag](https://cloud.githubusercontent.com/assets/22010995/21136311/484f0d28-c10c-11e6-8524-3c3f0b4eb636.jpg)

**Comment by Kathanious** [comment]
Ya, all of the new GQ artifacts are fubar. Will be fixed in next release.
